# Generated by Django 5.2.3 on 2025-08-07 08:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
        migrations.RenameIndex(
            model_name='image',
            new_name='images_imag_created_d57897_idx',
            old_name='images_imag_created_b41a97_idx',
        ),
    ]
